name = "sports-point"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "./"

[env.production]
routes = [
  { pattern = "example.com", zone_name = "example.com" }
]

[triggers.crons]
# Add cron jobs if needed
