/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolleyballRouteImport } from './routes/volleyball'
import { Route as TeamJerseysRouteImport } from './routes/team-jerseys'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndoorGamesRouteImport } from './routes/indoor-games'
import { Route as FootballRouteImport } from './routes/football'
import { Route as CricketRouteImport } from './routes/cricket'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChessRouteImport } from './routes/chess'
import { Route as CarromRouteImport } from './routes/carrom'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as BadmintonRouteImport } from './routes/badminton'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const VolleyballRoute = VolleyballRouteImport.update({
  id: '/volleyball',
  path: '/volleyball',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamJerseysRoute = TeamJerseysRouteImport.update({
  id: '/team-jerseys',
  path: '/team-jerseys',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndoorGamesRoute = IndoorGamesRouteImport.update({
  id: '/indoor-games',
  path: '/indoor-games',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketRoute = CricketRouteImport.update({
  id: '/cricket',
  path: '/cricket',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessRoute = ChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const CarromRoute = CarromRouteImport.update({
  id: '/carrom',
  path: '/carrom',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const BadmintonRoute = BadmintonRouteImport.update({
  id: '/badminton',
  path: '/badminton',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/carrom': typeof CarromRoute
  '/chess': typeof ChessRoute
  '/contact': typeof ContactRoute
  '/cricket': typeof CricketRoute
  '/football': typeof FootballRoute
  '/indoor-games': typeof IndoorGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-jerseys': typeof TeamJerseysRoute
  '/volleyball': typeof VolleyballRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/carrom': typeof CarromRoute
  '/chess': typeof ChessRoute
  '/contact': typeof ContactRoute
  '/cricket': typeof CricketRoute
  '/football': typeof FootballRoute
  '/indoor-games': typeof IndoorGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-jerseys': typeof TeamJerseysRoute
  '/volleyball': typeof VolleyballRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/carrom': typeof CarromRoute
  '/chess': typeof ChessRoute
  '/contact': typeof ContactRoute
  '/cricket': typeof CricketRoute
  '/football': typeof FootballRoute
  '/indoor-games': typeof IndoorGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-jerseys': typeof TeamJerseysRoute
  '/volleyball': typeof VolleyballRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badminton'
    | '/basketball'
    | '/carrom'
    | '/chess'
    | '/contact'
    | '/cricket'
    | '/football'
    | '/indoor-games'
    | '/sitemap.xml'
    | '/team-jerseys'
    | '/volleyball'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badminton'
    | '/basketball'
    | '/carrom'
    | '/chess'
    | '/contact'
    | '/cricket'
    | '/football'
    | '/indoor-games'
    | '/sitemap.xml'
    | '/team-jerseys'
    | '/volleyball'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/badminton'
    | '/basketball'
    | '/carrom'
    | '/chess'
    | '/contact'
    | '/cricket'
    | '/football'
    | '/indoor-games'
    | '/sitemap.xml'
    | '/team-jerseys'
    | '/volleyball'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadmintonRoute: typeof BadmintonRoute
  BasketballRoute: typeof BasketballRoute
  CarromRoute: typeof CarromRoute
  ChessRoute: typeof ChessRoute
  ContactRoute: typeof ContactRoute
  CricketRoute: typeof CricketRoute
  FootballRoute: typeof FootballRoute
  IndoorGamesRoute: typeof IndoorGamesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamJerseysRoute: typeof TeamJerseysRoute
  VolleyballRoute: typeof VolleyballRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volleyball': {
      id: '/volleyball'
      path: '/volleyball'
      fullPath: '/volleyball'
      preLoaderRoute: typeof VolleyballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-jerseys': {
      id: '/team-jerseys'
      path: '/team-jerseys'
      fullPath: '/team-jerseys'
      preLoaderRoute: typeof TeamJerseysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indoor-games': {
      id: '/indoor-games'
      path: '/indoor-games'
      fullPath: '/indoor-games'
      preLoaderRoute: typeof IndoorGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket': {
      id: '/cricket'
      path: '/cricket'
      fullPath: '/cricket'
      preLoaderRoute: typeof CricketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess': {
      id: '/chess'
      path: '/chess'
      fullPath: '/chess'
      preLoaderRoute: typeof ChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrom': {
      id: '/carrom'
      path: '/carrom'
      fullPath: '/carrom'
      preLoaderRoute: typeof CarromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badminton': {
      id: '/badminton'
      path: '/badminton'
      fullPath: '/badminton'
      preLoaderRoute: typeof BadmintonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadmintonRoute: BadmintonRoute,
  BasketballRoute: BasketballRoute,
  CarromRoute: CarromRoute,
  ChessRoute: ChessRoute,
  ContactRoute: ContactRoute,
  CricketRoute: CricketRoute,
  FootballRoute: FootballRoute,
  IndoorGamesRoute: IndoorGamesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamJerseysRoute: TeamJerseysRoute,
  VolleyballRoute: VolleyballRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
